/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type OgImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  _type: "image";
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  bio?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  category: "web" | "redes" | "diseno";
  accent?: "cyan" | "purple" | "orange" | "lime";
  orden?: number;
  socials?: {
    tiktok?: string;
    instagram?: string;
    linkedin?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  keyword?: string;
  autor?: string;
  author?: AuthorReference;
  fecha: string;
  featured?: boolean;
  categoriaServicio?: ServiceReference;
  categoriaIndustria?: IndustryReference;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: OgImage;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug?: Slug;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cliente: string;
  slug: Slug;
  industria: IndustryReference;
  servicios?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  resultadoFrase: string;
  titulo: string;
  resumen: string;
  destacado?: boolean;
  accent?: "cyan" | "orange" | "purple";
  metricas?: Array<
    {
      _key: string;
    } & Metric
  >;
  reto?: string;
  estrategia?: string;
  fases?: Array<
    {
      _key: string;
    } & TitledBlock
  >;
  testimonio?: {
    quote?: string;
    name?: string;
    role?: string;
  };
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: OgImage;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombre: string;
  slug: Slug;
  orden: number;
  tagline: string;
  heroTitle: string;
  heroDescription: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroBadge?: string;
  retos?: Array<string>;
  porQue?: Array<
    {
      _key: string;
    } & TitledBlock
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  serviceBlurbs?: Array<
    {
      _key: string;
    } & ServiceBlurb
  >;
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: OgImage;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle: string;
  heroDescription?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  historyEyebrow?: string;
  historyTitle?: string;
  historyDescription?: string;
  historyColumns?: Array<{
    title?: string;
    paragraphs?: Array<string>;
    _key: string;
  }>;
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: OgImage;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle: string;
  heroLead?: string;
  primaryCta?: Cta;
  secondaryCta?: Cta;
  process?: Array<
    {
      _key: string;
    } & ProcessStep
  >;
  faqCategories?: Array<
    {
      _key: string;
    } & FaqCategory
  >;
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: OgImage;
};

export type Cta = {
  _type: "cta";
  label: string;
  href: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  legalName: string;
  tagline: string;
  email?: string;
  phone?: string;
  phoneHref?: string;
  whatsapp?: string;
  locales?: Array<string>;
  socials?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: OgImage;
};

export type ServiceBlurb = {
  _type: "serviceBlurb";
  service: ServiceReference;
  description: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nombre: string;
  slug: Slug;
  orden: number;
  tagline: string;
  heroTitle: string;
  heroDescription?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroBadge?: string;
  cards?: Array<
    {
      _key: string;
    } & TitledBlock
  >;
  proceso?: Array<
    {
      _key: string;
    } & TitledBlock
  >;
  faqs?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: OgImage;
};

export type FaqCategory = {
  _type: "faqCategory";
  id: string;
  label: string;
  items?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type Metric = {
  _type: "metric";
  valor: number;
  label: string;
  prefix?: string;
  suffix?: string;
  decimals?: number;
  antes?: string;
  despues?: string;
};

export type ProcessStep = {
  _type: "processStep";
  index?: string;
  title: string;
  description: string;
};

export type TitledBlock = {
  _type: "titledBlock";
  title: string;
  description: string;
};

export type FaqItem = {
  _type: "faqItem";
  question: string;
  answer: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | OgImage
  | Person
  | SanityImageCrop
  | SanityImageHotspot
  | AuthorReference
  | ServiceReference
  | IndustryReference
  | Post
  | Slug
  | Author
  | CaseStudy
  | Industry
  | AboutPage
  | HomePage
  | Cta
  | SiteSettings
  | ServiceBlurb
  | Service
  | FaqCategory
  | Metric
  | ProcessStep
  | TitledBlock
  | FaqItem
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{  name,  legalName,  tagline,  email,  phone,  phoneHref,  whatsapp,  locales,  socials[]{ label, href },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type SiteSettingsQueryResult = {
  name: string;
  legalName: string;
  tagline: string;
  email: string | null;
  phone: string | null;
  phoneHref: string | null;
  whatsapp: string | null;
  locales: Array<string> | null;
  socials: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage" && _id == "homePage"][0]{  heroTitle,  heroLead,  primaryCta{ label, href },  secondaryCta{ label, href },  process[]{ index, title, description },  faqCategories[]{ id, label, items[]{ question, answer } },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type HomePageQueryResult = {
  heroTitle: string;
  heroLead: string | null;
  primaryCta: {
    label: string;
    href: string;
  } | null;
  secondaryCta: {
    label: string;
    href: string;
  } | null;
  process: Array<{
    index: string | null;
    title: string;
    description: string;
  }> | null;
  faqCategories: Array<{
    id: string;
    label: string;
    items: Array<{
      question: string;
      answer: string;
    }> | null;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{  heroTitle,  heroDescription,  heroImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  historyEyebrow,  historyTitle,  historyDescription,  historyColumns[]{ title, paragraphs },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type AboutPageQueryResult = {
  heroTitle: string;
  heroDescription: string | null;
  heroImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  historyEyebrow: string | null;
  historyTitle: string | null;
  historyDescription: string | null;
  historyColumns: Array<{
    title: string | null;
    paragraphs: Array<string> | null;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: industriesQuery
// Query: *[  _type == "industry" && defined(slug.current)] | order(orden asc) {  "id": slug.current,  nombre,  orden,  tagline,  heroTitle,  heroDescription,  heroImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  heroBadge,  retos,  porQue[]{ title, description },  faqs[]{ question, answer },  serviceBlurbs[]{    "serviceSlug": service->slug.current,    description  },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type IndustriesQueryResult = Array<{
  id: string;
  nombre: string;
  orden: number;
  tagline: string;
  heroTitle: string;
  heroDescription: string;
  heroImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  heroBadge: string | null;
  retos: Array<string> | null;
  porQue: Array<{
    title: string;
    description: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  serviceBlurbs: Array<{
    serviceSlug: string;
    description: string;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: industryBySlugQuery
// Query: *[  _type == "industry" && slug.current == $slug][0]{  "id": slug.current,  nombre,  orden,  tagline,  heroTitle,  heroDescription,  heroImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  heroBadge,  retos,  porQue[]{ title, description },  faqs[]{ question, answer },  serviceBlurbs[]{    "serviceSlug": service->slug.current,    description  },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type IndustryBySlugQueryResult = {
  id: string;
  nombre: string;
  orden: number;
  tagline: string;
  heroTitle: string;
  heroDescription: string;
  heroImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  heroBadge: string | null;
  retos: Array<string> | null;
  porQue: Array<{
    title: string;
    description: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  serviceBlurbs: Array<{
    serviceSlug: string;
    description: string;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: servicesQuery
// Query: *[  _type == "service" && defined(slug.current)] | order(orden asc) {  "id": slug.current,  nombre,  orden,  tagline,  heroTitle,  heroDescription,  heroImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  heroBadge,  cards[]{ title, description },  proceso[]{ title, description },  faqs[]{ question, answer },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type ServicesQueryResult = Array<{
  id: string;
  nombre: string;
  orden: number;
  tagline: string;
  heroTitle: string;
  heroDescription: string | null;
  heroImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  heroBadge: string | null;
  cards: Array<{
    title: string;
    description: string;
  }> | null;
  proceso: Array<{
    title: string;
    description: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: serviceBySlugQuery
// Query: *[  _type == "service" && slug.current == $slug][0]{  "id": slug.current,  nombre,  orden,  tagline,  heroTitle,  heroDescription,  heroImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  heroBadge,  cards[]{ title, description },  proceso[]{ title, description },  faqs[]{ question, answer },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type ServiceBySlugQueryResult = {
  id: string;
  nombre: string;
  orden: number;
  tagline: string;
  heroTitle: string;
  heroDescription: string | null;
  heroImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  heroBadge: string | null;
  cards: Array<{
    title: string;
    description: string;
  }> | null;
  proceso: Array<{
    title: string;
    description: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: casesQuery
// Query: *[  _type == "caseStudy" && defined(slug.current)]{  "id": slug.current,  cliente,  "industria": { "id": industria->slug.current },  "servicios": servicios[]->{ "id": slug.current, nombre, heroImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }} },  resultadoFrase,  titulo,  resumen,  destacado,  accent,  metricas[]{ valor, label, prefix, suffix, decimals, antes, despues },  reto,  estrategia,  fases[]{ title, description },  testimonio{ quote, name, role },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type CasesQueryResult = Array<{
  id: string;
  cliente: string;
  industria: {
    id: string;
  };
  servicios: Array<{
    id: string;
    nombre: string;
    heroImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  }> | null;
  resultadoFrase: string;
  titulo: string;
  resumen: string;
  destacado: boolean | null;
  accent: "cyan" | "orange" | "purple" | null;
  metricas: Array<{
    valor: number;
    label: string;
    prefix: string | null;
    suffix: string | null;
    decimals: number | null;
    antes: string | null;
    despues: string | null;
  }> | null;
  reto: string | null;
  estrategia: string | null;
  fases: Array<{
    title: string;
    description: string;
  }> | null;
  testimonio: {
    quote: string | null;
    name: string | null;
    role: string | null;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: caseBySlugQuery
// Query: *[  _type == "caseStudy" && slug.current == $slug][0]{  "id": slug.current,  cliente,  "industria": { "id": industria->slug.current },  "servicios": servicios[]->{ "id": slug.current, nombre, heroImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }} },  resultadoFrase,  titulo,  resumen,  destacado,  accent,  metricas[]{ valor, label, prefix, suffix, decimals, antes, despues },  reto,  estrategia,  fases[]{ title, description },  testimonio{ quote, name, role },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type CaseBySlugQueryResult = {
  id: string;
  cliente: string;
  industria: {
    id: string;
  };
  servicios: Array<{
    id: string;
    nombre: string;
    heroImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  }> | null;
  resultadoFrase: string;
  titulo: string;
  resumen: string;
  destacado: boolean | null;
  accent: "cyan" | "orange" | "purple" | null;
  metricas: Array<{
    valor: number;
    label: string;
    prefix: string | null;
    suffix: string | null;
    decimals: number | null;
    antes: string | null;
    despues: string | null;
  }> | null;
  reto: string | null;
  estrategia: string | null;
  fases: Array<{
    title: string;
    description: string;
  }> | null;
  testimonio: {
    quote: string | null;
    name: string | null;
    role: string | null;
  } | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: postsQuery
// Query: *[  _type == "post" && defined(slug.current)] | order(fecha desc) {  "id": slug.current,  title,  description,  keyword,  autor,  "authorName": coalesce(author->name, autor),  fecha,  featured,  "categoriaServicio": { "id": categoriaServicio->slug.current },  "categoriaIndustria": { "id": categoriaIndustria->slug.current },  cover {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  faqs[]{ question, answer },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type PostsQueryResult = Array<{
  id: string;
  title: string;
  description: string;
  keyword: string | null;
  autor: string | null;
  authorName: string | null;
  fecha: string;
  featured: boolean | null;
  categoriaServicio: {
    id: string | null;
  };
  categoriaIndustria: {
    id: string | null;
  };
  cover: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: postBySlugQuery
// Query: *[  _type == "post" && slug.current == $slug][0]{  "id": slug.current,  title,  description,  keyword,  autor,  "authorName": coalesce(author->name, autor),  fecha,  featured,  "categoriaServicio": { "id": categoriaServicio->slug.current },  "categoriaIndustria": { "id": categoriaIndustria->slug.current },  cover {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  body,  faqs[]{ question, answer },    metaTitle,  metaDescription,  ogImage {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }}}
export type PostBySlugQueryResult = {
  id: string;
  title: string;
  description: string;
  keyword: string | null;
  autor: string | null;
  authorName: string | null;
  fecha: string;
  featured: boolean | null;
  categoriaServicio: {
    id: string | null;
  };
  categoriaIndustria: {
    id: string | null;
  };
  cover: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  faqs: Array<{
    question: string;
    answer: string;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown; // Unable to locate the referenced type "media" in schema
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: peopleQuery
// Query: *[  _type == "person" && defined(name)] | order(orden asc) {  name,  role,  bio,  photo {  ...,  alt,  asset->{    _id,    url,    metadata { lqip, dimensions }  }},  category,  accent,  socials{ tiktok, instagram, linkedin }}
export type PeopleQueryResult = Array<{
  name: string;
  role: string;
  bio: string | null;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  category: "diseno" | "redes" | "web";
  accent: "cyan" | "lime" | "orange" | "purple" | null;
  socials: {
    tiktok: string | null;
    instagram: string | null;
    linkedin: string | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: sitemapEntriesQuery
// Query: {  "industries": *[_type == "industry" && defined(slug.current)]{ "slug": slug.current, _updatedAt },  "services": *[_type == "service" && defined(slug.current)]{ "slug": slug.current, _updatedAt },  "cases": *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current, _updatedAt },  "posts": *[_type == "post" && defined(slug.current)]{ "slug": slug.current, _updatedAt }}
export type SitemapEntriesQueryResult = {
  industries: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  services: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  cases: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  posts: Array<{
    slug: string;
    _updatedAt: string;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]{\n  name,\n  legalName,\n  tagline,\n  email,\n  phone,\n  phoneHref,\n  whatsapp,\n  locales,\n  socials[]{ label, href },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': SiteSettingsQueryResult;
    '*[_type == "homePage" && _id == "homePage"][0]{\n  heroTitle,\n  heroLead,\n  primaryCta{ label, href },\n  secondaryCta{ label, href },\n  process[]{ index, title, description },\n  faqCategories[]{ id, label, items[]{ question, answer } },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': HomePageQueryResult;
    '*[_type == "aboutPage" && _id == "aboutPage"][0]{\n  heroTitle,\n  heroDescription,\n  heroImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  historyEyebrow,\n  historyTitle,\n  historyDescription,\n  historyColumns[]{ title, paragraphs },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': AboutPageQueryResult;
    '*[\n  _type == "industry" && defined(slug.current)\n] | order(orden asc) {\n  "id": slug.current,\n  nombre,\n  orden,\n  tagline,\n  heroTitle,\n  heroDescription,\n  heroImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  heroBadge,\n  retos,\n  porQue[]{ title, description },\n  faqs[]{ question, answer },\n  serviceBlurbs[]{\n    "serviceSlug": service->slug.current,\n    description\n  },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': IndustriesQueryResult;
    '*[\n  _type == "industry" && slug.current == $slug\n][0]{\n  "id": slug.current,\n  nombre,\n  orden,\n  tagline,\n  heroTitle,\n  heroDescription,\n  heroImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  heroBadge,\n  retos,\n  porQue[]{ title, description },\n  faqs[]{ question, answer },\n  serviceBlurbs[]{\n    "serviceSlug": service->slug.current,\n    description\n  },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': IndustryBySlugQueryResult;
    '*[\n  _type == "service" && defined(slug.current)\n] | order(orden asc) {\n  "id": slug.current,\n  nombre,\n  orden,\n  tagline,\n  heroTitle,\n  heroDescription,\n  heroImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  heroBadge,\n  cards[]{ title, description },\n  proceso[]{ title, description },\n  faqs[]{ question, answer },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': ServicesQueryResult;
    '*[\n  _type == "service" && slug.current == $slug\n][0]{\n  "id": slug.current,\n  nombre,\n  orden,\n  tagline,\n  heroTitle,\n  heroDescription,\n  heroImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  heroBadge,\n  cards[]{ title, description },\n  proceso[]{ title, description },\n  faqs[]{ question, answer },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': ServiceBySlugQueryResult;
    '*[\n  _type == "caseStudy" && defined(slug.current)\n]{\n  "id": slug.current,\n  cliente,\n  "industria": { "id": industria->slug.current },\n  "servicios": servicios[]->{ "id": slug.current, nombre, heroImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n} },\n  resultadoFrase,\n  titulo,\n  resumen,\n  destacado,\n  accent,\n  metricas[]{ valor, label, prefix, suffix, decimals, antes, despues },\n  reto,\n  estrategia,\n  fases[]{ title, description },\n  testimonio{ quote, name, role },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': CasesQueryResult;
    '*[\n  _type == "caseStudy" && slug.current == $slug\n][0]{\n  "id": slug.current,\n  cliente,\n  "industria": { "id": industria->slug.current },\n  "servicios": servicios[]->{ "id": slug.current, nombre, heroImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n} },\n  resultadoFrase,\n  titulo,\n  resumen,\n  destacado,\n  accent,\n  metricas[]{ valor, label, prefix, suffix, decimals, antes, despues },\n  reto,\n  estrategia,\n  fases[]{ title, description },\n  testimonio{ quote, name, role },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': CaseBySlugQueryResult;
    '*[\n  _type == "post" && defined(slug.current)\n] | order(fecha desc) {\n  "id": slug.current,\n  title,\n  description,\n  keyword,\n  autor,\n  "authorName": coalesce(author->name, autor),\n  fecha,\n  featured,\n  "categoriaServicio": { "id": categoriaServicio->slug.current },\n  "categoriaIndustria": { "id": categoriaIndustria->slug.current },\n  cover {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  faqs[]{ question, answer },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': PostsQueryResult;
    '*[\n  _type == "post" && slug.current == $slug\n][0]{\n  "id": slug.current,\n  title,\n  description,\n  keyword,\n  autor,\n  "authorName": coalesce(author->name, autor),\n  fecha,\n  featured,\n  "categoriaServicio": { "id": categoriaServicio->slug.current },\n  "categoriaIndustria": { "id": categoriaIndustria->slug.current },\n  cover {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  body,\n  faqs[]{ question, answer },\n  \n  metaTitle,\n  metaDescription,\n  ogImage {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n}\n\n}': PostBySlugQueryResult;
    '*[\n  _type == "person" && defined(name)\n] | order(orden asc) {\n  name,\n  role,\n  bio,\n  photo {\n  ...,\n  alt,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  }\n},\n  category,\n  accent,\n  socials{ tiktok, instagram, linkedin }\n}': PeopleQueryResult;
    '{\n  "industries": *[_type == "industry" && defined(slug.current)]{ "slug": slug.current, _updatedAt },\n  "services": *[_type == "service" && defined(slug.current)]{ "slug": slug.current, _updatedAt },\n  "cases": *[_type == "caseStudy" && defined(slug.current)]{ "slug": slug.current, _updatedAt },\n  "posts": *[_type == "post" && defined(slug.current)]{ "slug": slug.current, _updatedAt }\n}': SitemapEntriesQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
